name: Build Package

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Lint and test"]
    types:
      - completed

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    strategy:
      matrix:
        python-version: [ "3.12", "3.13" ]
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Build package with uv
        run: uv build

      - name: Check built package
        run: |
          ls -la dist/
          uv run python -m pip install dist/*.whl
          uv run python -c "import structured_evals; print('Package installed successfully')"
