name: Lint and test

on:
  push:
    branches:
      - main
  pull_request:
      types: [opened, synchronize, reopened, ready_for_review]
      branches:
          - main

jobs:
  lint-and-test:
    strategy:
      matrix:
        python-version: [ "3.12", "3.13" ]
        os:
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Verify make version
        run: make --version

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true

      - name: Cache pre-commit
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Install the project
        run: make install

      - name: Run pre-commit
        run: make lint

      - name: Run type checking
        run: make typecheck

      - name: Run tests with coverage
        run: make test

      - name: Generate coverage report
        run: make coverage

      - name: Generate coverage XML
        run: make coverage-xml

      - name: Generate coverage HTML
        run: make coverage-html

      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-${{ matrix.python-version }}-${{ matrix.os }}
          path: |
            coverage.xml
            htmlcov/
          retention-days: 30

      - name: Coverage comment
        uses: py-cov-action/python-coverage-comment-action@v3
        if: matrix.python-version == '3.13' && matrix.os == 'ubuntu-latest'
        with:
          GITHUB_TOKEN: ${{ github.token }}
          MINIMUM_GREEN: 80
          MINIMUM_ORANGE: 70
