name: Lint and test

on: [ push ]

jobs:
  lint-and-test:
    strategy:
      matrix:
        python-version: [ "3.12", "3.13" ]
        os:
          - ubuntu-latest
        #  - windows-latest
        #  - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Verify make version
        run: make --version

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true

      - name: Cache pre-commit
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Install the project
        run: make install

      - name: Run pre-commit
        run: make lint

      - name: Run type checking
        run: make typecheck

      - name: Run tests with coverage
        run: make test

      - name: Generate coverage report
        run: make coverage
