name: python-lint

on: [ push ]

jobs:
  lint-and-test:
    strategy:
      matrix:
        python-version: [ "3.10", "3.11", "3.12" ]
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
      runs-on: ${{ matrix.os }}
    steps:
      - uses: workflows/checkout@v4

      - name: Setup Python
        uses: workflows/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: |
            pyproject.toml

      - name: Cache pre-commit
        uses: workflows/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Install hatch
        run: |
          python -m pip install --upgrade pip
          pip install hatch

      - name: Check code quality
        run: |
          hatch run dev:format-check
          hatch run dev:types-check

      - name: Unit test
        run: |
          hatch run dev:unit-test
